export {}
let message = "Welcome back";
console.log(message)

let isBeginner: boolean = true;
let total: number = 0;
let name: string = "Vas";

let sentence: string = `My name is ${name}`;

console.log(sentence);

let u: undefined = undefined;

let isNew: boolean = null;
let list1: number[] = [1,2,3,4];

enum Color {Red, Blue, Orange};

let c: Color = Color.Blue;

let myVariable: unknown = 10;
console.log(myVariable)

var sup: string = "Hello World";

class Greeting { 
    greet():void { 
       console.log("Hello World!!!") 
    } 
 } 
 var obj = new Greeting(); 
 obj.greet();

 
var msg:string = "hello"+"world" 

var num:number = -2 
var result = num > 0 ?"positive":"non-positive" 
console.log(result)

var num = -2;
var result = num > 0 ? "positive" : "non-positive";
console.log(result);

var num = 12 

var n:number = 5 
while(n > 5) { 
   console.log("Entered while") 
} 
do { 
   console.log("Entered do…while") 
} 
while(n>5)

var i:number = 1 
while(i<=10) { 
   if (i % 5 == 0) {   
      console.log ("The first multiple of 5  between 1 and 10 is : "+i) 
      break     //exit the loop if the first multiple is found 
   } 
   i++ 
}  //outputs 5 and exits the loo

function disp_details2(id:number,name:string,mail_id?:string) { 
    console.log("ID:", id); 
    console.log("Name",name); 
    
    if(mail_id!=undefined)  
    console.log("Email Id",mail_id); 
 }
 disp_details2(123,"John");
 disp_details2(111,"mary","mary@xyz.com");

 //Generated by typescript 1.8.10
function disp_details1(id, name, mail_id) {
    console.log("ID:", id);
    console.log("Name", name);
     
    if (mail_id != undefined)
       console.log("Email Id", mail_id);
 }
 disp_details2(123, "John");
 disp_details2(111, "mary", "mary@xyz.com");

 function addNumbers(...nums:number[]) {  
    var i;   
    var sum:number = 0; 
    
    for(i = 0;i<nums.length;i++) { 
       sum = sum + nums[i]; 
    } 
    console.log("sum of the numbers",sum) 
 } 
 addNumbers(1,2,3) 
 addNumbers(10,10,10,10,10)

 //Generated by typescript 1.8.10
var names = new Array("Mary", "Tom", "Jack", "Jill");
for (var i = 0; i < names.length; i++) {
   console.log(names[i]);
}

var arr:number[] = [12,13] 
var[x,y] = arr 
console.log(x) 
console.log(y)

var mytuple = [10,"Hello","World","typeScript"]; 
console.log("Items before push "+mytuple.length)    // returns the tuple size 

mytuple.push(12)                                    // append value to the tuple 
console.log("Items after push "+mytuple.length) 
console.log("Items before pop "+mytuple.length) 
console.log(mytuple.pop()+" popped from the tuple") // removes and returns the last item
  
console.log("Items after pop "+mytuple.length)

// union example
var val:string|number 
val = 12 
console.log("numeric value of val "+val) 
val = "This is a string" 
console.log("string value of val "+val)

function disp(name:string|string[]) { 
    if(typeof name == "string") { 
       console.log(name) 
    } else { 
       var i; 
       
       for(i = 0;i<name.length;i++) { 
          console.log(name[i])
       } 
    } 
 } 
 disp("mark") 
 console.log("Printing names array....") 
 disp(["Mark","Tom","Mary","John"])

 //Generated by typescript 1.8.10
var customer = { firstName: "Tom", lastName: "Hanks",
sayHi: function () { return "Hi there"; }
};
console.log("Customer Object ");
console.log(customer.firstName);
console.log(customer.lastName);
console.log(customer.sayHi());
var employee = { firstName: "Jim", lastName: "Blakes",
sayHi: function () { return "Hello!!!"; } };

console.log("Employee  Object ");
console.log(employee.firstName);
console.log(employee.lastName);

// object class example

//Generated by typescript 1.8.10
var Car = (function () {
    //constructor
    function Car(engine) {
       this.engine = engine;
    }
     
    //function
    Car.prototype.disp = function () {
       console.log("Engine is  :   " + this.engine);
    };
    return Car;
 }());

 class Shape { 
    Area:number 
    
    constructor(a:number) { 
       this.Area = a 
    } 
 } 
 
 class Circle extends Shape { 
    disp():void { 
       console.log("Area of the circle:  "+this.Area) 
    } 
 }
   
 var bro = new Circle(223); 
 bro.disp()

//  objects practice
var person = { 
    firstname:"Tom", 
    lastname:"Hanks" 
 }; 
 var invokeperson = function(obj: { firstname:string, lastname :string }) { 
    console.log("first name :"+obj.firstname) 
    console.log("last name :"+obj.lastname) 
 } 
 invokeperson(person)

 namespace SomeNameSpaceName { 
    export interface ISomeInterfaceName {      }  
    export class SomeClassName {      }  
 } 